name: Deploy to Vercel

on:
  push:
    branches:
      - main # Thay thế bằng branch bạn muốn deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Chọn phiên bản Node.js bạn muốn

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: lBJvX0bEgWVifttyYENNoira
        run: |
          npm install -g vercel
          vercel --prod --token $VERCEL_TOKEN
